######################################
#
# sfizz-labs
#
######################################

SFIZZ_LABS_VERSION = a6b38b8268e7d5f15a961e89b2d8822747ce67c3
SFIZZ_LABS_SITE = https://github.com/sfztools/sfizz-ui.git
SFIZZ_LABS_SITE_METHOD = git
SFIZZ_LABS_DEPENDENCIES = host-cmake
SFIZZ_LABS_CONF_OPTS  = -DSFIZZ_JACK=OFF
SFIZZ_LABS_CONF_OPTS += -DSFIZZ_RENDER=OFF
SFIZZ_LABS_CONF_OPTS += -DPLUGIN_LV2_PSA=OFF
SFIZZ_LABS_CONF_OPTS += -DPLUGIN_LV2_UI=OFF
SFIZZ_LABS_CONF_OPTS += -DPLUGIN_VST2=OFF
SFIZZ_LABS_CONF_OPTS += -DPLUGIN_VST3=OFF
SFIZZ_LABS_CONF_OPTS += -DSFIZZ_SHARED=OFF
SFIZZ_LABS_CONF_OPTS += -DBUILD_SHARED_LIBS=FALSE
SFIZZ_LABS_CONF_OPTS += -DCOMPILER_SUPPORTS_SYMBOL_MAPS_EXITCODE=1
SFIZZ_LABS_CONF_OPTS += -DCOMPILER_SUPPORTS_SYMBOL_MAPS_EXITCODE__TRYRUN_OUTPUT="FAILED_TO_RUN"
SFIZZ_LABS_BUNDLES = sfizz.lv2

# needed for submodules support
SFIZZ_LABS_PRE_DOWNLOAD_HOOKS += MOD_PLUGIN_BUILDER_DOWNLOAD_WITH_SUBMODULES

define SFIZZ_LABS_POST_INSTALL_TARGET_TTLFILES
	cp -rL $($(PKG)_PKGDIR)/sfizz.lv2/* $(TARGET_DIR)/usr/lib/lv2/sfizz.lv2/
endef

SFIZZ_LABS_POST_INSTALL_TARGET_HOOKS += SFIZZ_LABS_POST_INSTALL_TARGET_TTLFILES

$(eval $(cmake-package))
