######################################
#
# gxswitchlesswah
#
######################################

GXSWITCHLESSWAH_VERSION = 67c846ddc4966ad1112d15f8a82c55bd12f80fe3
GXSWITCHLESSWAH_SITE = $(call github,brummer10,GxSwitchlessWah.lv2,$(GXSWITCHLESSWAH_VERSION))
GXSWITCHLESSWAH_BUNDLES = GxSwitchlessWah.lv2

ifdef BR2_cortex_a7
GXSWITCHLESSWAH_SSE_CFLAGS = -mfpu=vfpv3
else
GXSWITCHLESSWAH_SSE_CFLAGS = ""
endif

GXSWITCHLESSWAH_TARGET_MAKE = $(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) SSE_CFLAGS="$(GXSWITCHLESSWAH_SSE_CFLAGS)" -C $(@D)

define GXSWITCHLESSWAH_BUILD_CMDS
	$(GXSWITCHLESSWAH_TARGET_MAKE) mod
endef

define GXSWITCHLESSWAH_INSTALL_TARGET_CMDS
	$(GXSWITCHLESSWAH_TARGET_MAKE) install DESTDIR=$(TARGET_DIR) INSTALL_DIR=/usr/lib/lv2
endef

$(eval $(generic-package))
