################################################################################
#
# carla-backend
#
################################################################################

CARLA_BACKEND_VERSION = 613e6950581ad0cb3c037fac7f0db89633e099e6
CARLA_BACKEND_SITE = $(call github,falkTX,Carla,$(CARLA_BACKEND_VERSION))

CARLA_BACKEND_EXTRAFLAGS += PREFIX=$(TARGET_DIR)/usr
CARLA_BACKEND_EXTRAFLAGS += CAN_GENERATE_LV2_TTL=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_ALSA=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_JACK=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_PULSEAUDIO=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_DGL=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_HYLIA=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_GTK2=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_GTK3=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_X11=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_FFMPEG=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_FLUIDSYNTH=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_LIBLO=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_LIBMAGIC=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_PYQT=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_QT=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_QT4=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_QT5=false
CARLA_BACKEND_EXTRAFLAGS += HAVE_SNDFILE=false
CARLA_BACKEND_EXTRAFLAGS += EXTERNAL_PLUGINS=false
CARLA_BACKEND_EXTRAFLAGS += USING_JUCE=false
CARLA_BACKEND_EXTRAFLAGS += USING_JUCE_AUDIO_DEVICES=false
CARLA_BACKEND_EXTRAFLAGS += USING_JUCE_GUI_EXTRA=false

ifeq ($(BR2_OPTIMIZE_0),y)
CARLA_BACKEND_EXTRAFLAGS += DEBUG=true
else
CARLA_BACKEND_EXTRAFLAGS += NOOPT=true
endif

CARLA_BACKEND_TARGET_MAKE = $(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D) $(CARLA_BACKEND_EXTRAFLAGS)

define CARLA_BACKEND_BUILD_CMDS
	$(CARLA_BACKEND_TARGET_MAKE)
endef

define CARLA_BACKEND_INSTALL_TARGET_CMDS
	$(CARLA_BACKEND_TARGET_MAKE) install
endef

$(eval $(generic-package))
