diff --git a/avocado/source/Makefile.mk b/avocado/source/Makefile.mk
index abec27e..08918cd 100644
--- a/avocado/source/Makefile.mk
+++ b/avocado/source/Makefile.mk
@@ -130,8 +130,7 @@ $(lv2_dsp): $(OBJS_DSP) $(DISTRHO_PLUGIN_FILES)
 	$(CXX) $^ $(BUILD_CXX_FLAGS) $(LINK_FLAGS) $(SHARED) -DDISTRHO_PLUGIN_TARGET_LV2 -o $@
 
 $(lv2_ttl): $(lv2_dsp) $(TARGET_DIR)/lv2_ttl_generator
-	cd $(TARGET_DIR)/$(NAME).lv2/ && \
-	../lv2_ttl_generator ./$(NAME)_dsp$(LIB_EXT)
+	cd $(TARGET_DIR)/$(NAME).lv2/ 
 
 $(TARGET_DIR)/lv2_ttl_generator:
 	mkdir -p $(shell dirname $@)

diff --git a/floaty/source/Makefile.mk b/floaty/source/Makefile.mk
index abec27e..08918cd 100644
--- a/floaty/source/Makefile.mk
+++ b/floaty/source/Makefile.mk
@@ -130,8 +130,7 @@ $(lv2_dsp): $(OBJS_DSP) $(DISTRHO_PLUGIN_FILES)
 	$(CXX) $^ $(BUILD_CXX_FLAGS) $(LINK_FLAGS) $(SHARED) -DDISTRHO_PLUGIN_TARGET_LV2 -o $@
 
 $(lv2_ttl): $(lv2_dsp) $(TARGET_DIR)/lv2_ttl_generator
-	cd $(TARGET_DIR)/$(NAME).lv2/ && \
-	../lv2_ttl_generator ./$(NAME)_dsp$(LIB_EXT)
+	cd $(TARGET_DIR)/$(NAME).lv2/ 
 
 $(TARGET_DIR)/lv2_ttl_generator:
 	mkdir -p $(shell dirname $@)

diff --git a/mud/source/Makefile.mk b/mud/source/Makefile.mk
index abec27e..08918cd 100644
--- a/mud/source/Makefile.mk
+++ b/mud/source/Makefile.mk
@@ -130,8 +130,7 @@ $(lv2_dsp): $(OBJS_DSP) $(DISTRHO_PLUGIN_FILES)
 	$(CXX) $^ $(BUILD_CXX_FLAGS) $(LINK_FLAGS) $(SHARED) -DDISTRHO_PLUGIN_TARGET_LV2 -o $@
 
 $(lv2_ttl): $(lv2_dsp) $(TARGET_DIR)/lv2_ttl_generator
-	cd $(TARGET_DIR)/$(NAME).lv2/ && \
-	../lv2_ttl_generator ./$(NAME)_dsp$(LIB_EXT)
+	cd $(TARGET_DIR)/$(NAME).lv2/ 
 
 $(TARGET_DIR)/lv2_ttl_generator:
 	mkdir -p $(shell dirname $@)

diff --git a/paranoia/source/Makefile.mk b/paranoia/source/Makefile.mk
index abec27e..08918cd 100644
--- a/paranoia/source/Makefile.mk
+++ b/paranoia/source/Makefile.mk
@@ -130,8 +130,7 @@ $(lv2_dsp): $(OBJS_DSP) $(DISTRHO_PLUGIN_FILES)
 	$(CXX) $^ $(BUILD_CXX_FLAGS) $(LINK_FLAGS) $(SHARED) -DDISTRHO_PLUGIN_TARGET_LV2 -o $@
 
 $(lv2_ttl): $(lv2_dsp) $(TARGET_DIR)/lv2_ttl_generator
-	cd $(TARGET_DIR)/$(NAME).lv2/ && \
-	../lv2_ttl_generator ./$(NAME)_dsp$(LIB_EXT)
+	cd $(TARGET_DIR)/$(NAME).lv2/ 
 
 $(TARGET_DIR)/lv2_ttl_generator:
 	mkdir -p $(shell dirname $@)
