#!/usr/bin/make -f
# Makefile for eg-amp.lv2 #
# ----------------------- #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = DPF-Amp

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	amp.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
