######################################
#
# gxvintagefuzzmaster
#
######################################

GXVINTAGEFUZZMASTER_VERSION = 8bec1997f6550f0188ac60a69158070cfb26d623
GXVINTAGEFUZZMASTER_SITE = $(call github,brummer10,GxVintageFuzzMaster.lv2,$(GXVINTAGEFUZZMASTER_VERSION))
GXVINTAGEFUZZMASTER_BUNDLES = gx_vfm.lv2

ifdef BR2_cortex_a7
GXVINTAGEFUZZMASTER_SSE_CFLAGS = -mfpu=vfpv3
endif

GXVINTAGEFUZZMASTER_TARGET_MAKE = $(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) SSE_CFLAGS="$(GXVINTAGEFUZZMASTER_SSE_CFLAGS)" -C $(@D)

define GXVINTAGEFUZZMASTER_BUILD_CMDS
	$(GXVINTAGEFUZZMASTER_TARGET_MAKE) mod
endef

define GXVINTAGEFUZZMASTER_INSTALL_TARGET_CMDS
	$(GXVINTAGEFUZZMASTER_TARGET_MAKE) install DESTDIR=$(TARGET_DIR) INSTALL_DIR=/usr/lib/lv2
	cp -rL $($(PKG)_PKGDIR)/gx_vfm.lv2/* $(TARGET_DIR)/usr/lib/lv2/gx_vfm.lv2/
endef

$(eval $(generic-package))
