######################################
#
# midi-display
#
######################################

VALLSV_MIDI_DISPLAY_LABS_VERSION = ccf031e74df96565aabb4af21cb4b7cf7bd07f0f
VALLSV_MIDI_DISPLAY_LABS_SITE = $(call github,vallsv,midi-display.lv2,$(VALLSV_MIDI_DISPLAY_LABS_VERSION))
VALLSV_MIDI_DISPLAY_LABS_DEPENDENCIES =
VALLSV_MIDI_DISPLAY_LABS_BUNDLES = midi-display.lv2

VALLSV_MIDI_DISPLAY_LABS_TARGET_MAKE = $(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) PREFIX=/usr -C $(@D)

define VALLSV_MIDI_DISPLAY_LABS_BUILD_CMDS
	$(VALLSV_MIDI_DISPLAY_LABS_TARGET_MAKE)
endef

define VALLSV_MIDI_DISPLAY_LABS_INSTALL_TARGET_CMDS
	$(VALLSV_MIDI_DISPLAY_LABS_TARGET_MAKE) install DESTDIR=$(TARGET_DIR)
endef

$(eval $(generic-package))
