######################################
#
# commercial-plugin-example
#
######################################

# where to find the source code - locally in this case
COMMERCIAL_PLUGIN_EXAMPLE_SITE_METHOD = local
COMMERCIAL_PLUGIN_EXAMPLE_SITE = $($(PKG)_PKGDIR)/

# even though this is a local build, we still need a version number
# bump this number if you need to force a rebuild
COMMERCIAL_PLUGIN_EXAMPLE_VERSION = 1

# dependencies (list of other buildroot packages, separated by space)
# commercial plugins require libmodla as dependency
COMMERCIAL_PLUGIN_EXAMPLE_DEPENDENCIES = libmodla

# LV2 bundles generated by this package (space separated list)
COMMERCIAL_PLUGIN_EXAMPLE_BUNDLES = commercial-plugin-example.lv2

# call make with the current arguments and path. "$(@D)" is the build directory.
COMMERCIAL_PLUGIN_EXAMPLE_TARGET_MAKE = $(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D)/source

# build command
define COMMERCIAL_PLUGIN_EXAMPLE_BUILD_CMDS
	$(COMMERCIAL_PLUGIN_EXAMPLE_TARGET_MAKE)
endef

# install command
define COMMERCIAL_PLUGIN_EXAMPLE_INSTALL_TARGET_CMDS
	$(COMMERCIAL_PLUGIN_EXAMPLE_TARGET_MAKE) install DESTDIR=$(TARGET_DIR)
endef

# import everything else from the buildroot generic package
$(eval $(generic-package))
