#!/usr/bin/make -f
# Makefile for eg-synth.lv2 #
# ------------------------- #
# Created by falkTX
#

# --------------------------------------------------------------
# Project name, used for binaries

NAME = DPF-Synth

# --------------------------------------------------------------
# Files to build

OBJS_DSP = \
	synth.cpp.o

# --------------------------------------------------------------
# Do some magic

include Makefile.mk

# --------------------------------------------------------------
