######################################
#
# neural-amp-modeler-lv2
#
######################################

NEURAL_AMP_MODELER_LV2_VERSION = f2cecf5491b59106c661e724809a8b7ae35e8d21
NEURAL_AMP_MODELER_LV2_SITE = https://github.com/mikeoliphant/neural-amp-modeler-lv2.git
NEURAL_AMP_MODELER_LV2_SITE_METHOD = git
NEURAL_AMP_MODELER_LV2_BUNDLES = neural_amp_modeler.lv2

# LTO-specific flags (must be present on build and link stage)
NEURAL_AMP_MODELER_LV2_LTO_FLAGS = -fno-strict-aliasing -flto -ffat-lto-objects

# pass options into cmake
NEURAL_AMP_MODELER_LV2_TARGET_OPT = $(subst ",,$(BR2_TARGET_OPTIMIZATION)) -fsingle-precision-constant -Wno-sign-compare
NEURAL_AMP_MODELER_LV2_CONF_OPTS += -DCMAKE_C_FLAGS_RELEASE="$(NEURAL_AMP_MODELER_LV2_TARGET_OPT) $(NEURAL_AMP_MODELER_LV2_LTO_FLAGS)"
NEURAL_AMP_MODELER_LV2_CONF_OPTS += -DCMAKE_CXX_FLAGS_RELEASE="$(NEURAL_AMP_MODELER_LV2_TARGET_OPT) $(NEURAL_AMP_MODELER_LV2_LTO_FLAGS)"
NEURAL_AMP_MODELER_LV2_CONF_OPTS += -DCMAKE_SHARED_LINKER_FLAGS_RELEASE="$(TARGET_LDFLAGS) $(NEURAL_AMP_MODELER_LV2_TARGET_OPT) $(NEURAL_AMP_MODELER_LV2_LTO_FLAGS)"

# needed for submodules support
NEURAL_AMP_MODELER_LV2_PRE_DOWNLOAD_HOOKS += MOD_PLUGIN_BUILDER_DOWNLOAD_WITH_SUBMODULES

define NEURAL_AMP_MODELER_LV2_INSTALL_TARGET_CMDS
	install -d $(TARGET_DIR)/usr/lib/lv2/$(NEURAL_AMP_MODELER_LV2_BUNDLES)/modgui
	install -m 644 $(@D)/$(NEURAL_AMP_MODELER_LV2_BUNDLES)/*.so $(TARGET_DIR)/usr/lib/lv2/$(NEURAL_AMP_MODELER_LV2_BUNDLES)/
	install -m 644 $($(PKG)_PKGDIR)/$(NEURAL_AMP_MODELER_LV2_BUNDLES)/*.* $(TARGET_DIR)/usr/lib/lv2/$(NEURAL_AMP_MODELER_LV2_BUNDLES)/
	install -m 644 $($(PKG)_PKGDIR)/$(NEURAL_AMP_MODELER_LV2_BUNDLES)/modgui/*.* $(TARGET_DIR)/usr/lib/lv2/$(NEURAL_AMP_MODELER_LV2_BUNDLES)/modgui/
endef

$(eval $(cmake-package))
